### PR TITLE
BLD: fix #158

### LINKED ISSUE #158: Use BN all along in workerSelection algo
Do not use `toNumber()` [here](https://github.com/enigmampc/enigma-p2p/blob/938f31348b87340f69a2727a67cd2c08d223611a/src/ethereum/EthereumVerifier.js#L368), and instead keep all the algebraic operations within the BN domain.

Otherwise we get this error:

```
p2p_2        | (node:65) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
p2p_2        |     at assert (/root/enigma-p2p/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
p2p_2        |     at BN.toNumber (/root/enigma-p2p/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
p2p_2        |     at Function.selectWorkerGroup (/root/enigma-p2p/src/ethereum/EthereumVerifier.js:368:80)
p2p_2        |     at EthereumVerifier._verifySelectedWorker (/root/enigma-p2p/src/ethereum/EthereumVerifier.js:336:43)
p2p_2        |     at Promise (/root/enigma-p2p/src/ethereum/EthereumVerifier.js:133:24)
p2p_2        |     at new Promise (<anonymous>)
p2p_2        |     at EthereumVerifier.verifySelectedWorker (/root/enigma-p2p/src/ethereum/EthereumVerifier.js:126:12)
p2p_2        |     at _verifyTaskCreationNow.then (/root/enigma-p2p/src/ethereum/EthereumVerifier.js:65:35)
p2p_2        |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
p2p_2        | (node:65) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
p2p_2        | (node:65) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
For a reference implementation in the contract, refer to [this](https://github.com/enigmampc/enigma-contract/blob/e7284d1d2068cab55c71e914a4efa5431dfbdd2a/enigma-js/src/Enigma.js#L364).

### PR DESCRIPTION
**Pull request by lacabra**
1. The changes in `src/ethereum/EthereumVerifier.js` fix #158.
2. Then got an error that balances was a string, so introduced changes in `src/ethereum/EnigmaContractReaderAPI.js` mapping the balances we get from the call to the contract to BigNumbers
3. Then the unit tests threw the following error:
```
(node:4839) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'negative' on number '1'
    at BN.isub (/home/eng-user/enigma-p2p/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:925:20)
    at BN.sub (/home/eng-user/enigma-p2p/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:989:25)
    at Function.selectWorkerGroup (/home/eng-user/enigma-p2p/src/ethereum/EthereumVerifier.js:373:27)
    at EthereumVerifier._verifySelectedWorker (/home/eng-user/enigma-p2p/src/ethereum/EthereumVerifier.js:335:43)
    at Promise (/home/eng-user/enigma-p2p/src/ethereum/EthereumVerifier.js:132:24)
    at new Promise (<anonymous>)
    at EthereumVerifier.verifySelectedWorker (/home/eng-user/enigma-p2p/src/ethereum/EthereumVerifier.js:125:12)
    at _verifyTaskCreationNow.then (/home/eng-user/enigma-p2p/src/ethereum/EthereumVerifier.js:64:35)
(node:4839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```
which according to [this thread](https://stackoverflow.com/questions/54604859/calling-web3-utils-bn-add-gives-error-cannot-create-property-negative-on-numb) was resolved by changing the BigNumber library, resulting in installing a new dependency (`package.json` & package-lock.json`) and changes to `src/common/cryptography.js`

All unit tests are passing locally.

### CODE REVIEW

**Comment by lacabra** [comment]
Changed the BigNumber library from `bignumber.js` to [JSBI](https://github.com/GoogleChromeLabs/jsbi).

Matches the implementation in the `Enigma.JS` library, as per this [PullRequest](https://github.com/enigmampc/enigma-contract/pull/84).

All unit tests are passing both in the P2P in this PR, and the counterpart in the library (see above).

File: src/ethereum/EthereumVerifier.js [hunk 1]
```diff
@@ -353,24 +355,24 @@ class EthereumVerifier {
...
+    const tokenCpt = params.balances.reduce((a, b) => JSBI.add(a, b), JSBI.BigInt(0));
     let nonce = 0;
     const selectedWorkers = [];
     do {
       // Unique hash for epoch, secret contract address, and nonce
-      const hash = cryptography.soliditySha3(
-        {t: 'uint256', v: params.seed},
-        {t: 'bytes32', v: secretContractAddress},
-        {t: 'uint256', v: nonce});
+      const hash = cryptography.hash(abi.rawEncode(
```
Comment (elichai) [inline src/ethereum/EthereumVerifier.js]: Can you elaborate on why the change in function?
this adds another dependency

Comment (lacabra) [reply src/ethereum/EthereumVerifier.js]: Because that's what the [contract](https://github.com/enigmampc/enigma-contract/blob/3048db58f1ccc0fe133e168f0e64e62b7322ce65/contracts/impl/WorkersImpl.sol#L240) and the [library](https://github.com/enigmampc/enigma-contract/blob/3048db58f1ccc0fe133e168f0e64e62b7322ce65/enigma-js/src/Enigma.js#L350) implement, and we need to match such implementations. We are not using `soliditySha3()` because under the hood that used `encodePacked`.

File: src/common/cryptography.js [hunk 2]
```diff
@@ -48,7 +48,7 @@ module.exports.hashArray = (inputsArray) => {
   for (let e of inputsArray) {
     e = utils.remove0x(e);
     // since the inputs are in hex string, they are twice as long as their bytes
-    hexStr += (new BN(e.length/2).toBuffer('be', 8).toString('hex')) + e;
+    hexStr += JSBI.BigInt(e.length/2).toString(16).padStart(16, '0') + e;
```
Comment (elichai) [inline src/common/cryptography.js]: I really preferred that it was explicitly saying BigEndian, but maybe this can be addressed in a different PR

Comment (elichai) [reply src/common/cryptography.js]: @lenak25

Comment (lacabra) [reply src/common/cryptography.js]: I understand, and I agree with you @elichai. I looked into JSBI, and there seems to be no explicit mention to "endianness" anywhere in the repo, so it must be using big endian by default, and there seems to be no way of specifying it.
